var searchData=
[
  ['ui_0',['Ui',['../namespace_ui.html',1,'']]],
  ['ui_5fadcionarfuncionarios_1',['Ui_AdcionarFuncionarios',['../class_ui___adcionar_funcionarios.html',1,'']]],
  ['ui_5fadcionarfuncionarios_2eh_2',['ui_adcionarfuncionarios.h',['../ui__adcionarfuncionarios_8h.html',1,'']]],
  ['ui_5fadproduto_3',['Ui_AdProduto',['../class_ui___ad_produto.html',1,'']]],
  ['ui_5fadproduto_2eh_4',['ui_adproduto.h',['../ui__adproduto_8h.html',1,'']]],
  ['ui_5fdadosdevenda_5',['Ui_DadosDeVenda',['../class_ui___dados_de_venda.html',1,'']]],
  ['ui_5fdadosdevenda_2eh_6',['ui_dadosdevenda.h',['../ui__dadosdevenda_8h.html',1,'']]],
  ['ui_5fexibirdadosdevenda_7',['Ui_ExibirDadosDeVenda',['../class_ui___exibir_dados_de_venda.html',1,'']]],
  ['ui_5fexibirdadosdevenda_2eh_8',['ui_exibirdadosdevenda.h',['../ui__exibirdadosdevenda_8h.html',1,'']]],
  ['ui_5fexibirestoque_9',['Ui_ExibirEstoque',['../class_ui___exibir_estoque.html',1,'']]],
  ['ui_5fexibirestoque_2eh_10',['ui_exibirestoque.h',['../ui__exibirestoque_8h.html',1,'']]],
  ['ui_5fmainwindow_11',['Ui_MainWindow',['../class_ui___main_window.html',1,'']]],
  ['ui_5fmainwindow_2eh_12',['ui_mainwindow.h',['../ui__mainwindow_8h.html',1,'']]],
  ['ui_5fproduto_13',['Ui_produto',['../class_ui__produto.html',1,'']]],
  ['ui_5fproduto_2eh_14',['ui_produto.h',['../ui__produto_8h.html',1,'']]],
  ['ui_5fremoveproduto_15',['Ui_RemoveProduto',['../class_ui___remove_produto.html',1,'']]],
  ['ui_5fremoveproduto_2eh_16',['ui_removeproduto.h',['../ui__removeproduto_8h.html',1,'']]],
  ['ui_5fvenderproduto_17',['Ui_venderproduto',['../class_ui__venderproduto.html',1,'']]],
  ['ui_5fvenderproduto_2eh_18',['ui_venderproduto.h',['../ui__venderproduto_8h.html',1,'']]],
  ['ui_5fvenderprodutos_19',['Ui_VenderProdutos',['../class_ui___vender_produtos.html',1,'']]],
  ['ui_5fvenderprodutos_2eh_20',['ui_venderprodutos.h',['../ui__venderprodutos_8h.html',1,'']]],
  ['um_20número_20específico_20de_20vendas_20o_20produto_20mais_20vendido_20o_20produto_20menos_20vendido_20e_20os_20demais_20com_20um_20cálculo_20em_20porcentagem_20das_20vendas_20de_20acordo_20com_20a_20quantidade_21',['_O programa apresentará ao final de um número específico de vendas, o produto mais vendido, o produto menos vendido e os demais com um cálculo em porcentagem das vendas de acordo com a quantidade.',['../md__c_1_2_users_2fcgam_2_one_drive_2_documentos_2_t_f_2_controle-de-estoque-e-vendas-de-loja_2_r_e_a_d_m_e.html#autotoc_md4',1,'']]],
  ['um_20programa_20capaz_20de_20realizar_20a_20administração_20da_20entrada_20e_20saída_20de_20produtos_20de_20uma_20loja_20sendo_20usado_20o_20exemplo_20de_20uma_20loja_20de_20eletrônicos_22',['_Neste projeto temos o intuito de criar um programa capaz de realizar a administração da entrada e saída de produtos de uma loja, sendo usado o exemplo de uma loja de eletrônicos.',['../md__c_1_2_users_2fcgam_2_one_drive_2_documentos_2_t_f_2_controle-de-estoque-e-vendas-de-loja_2_r_e_a_d_m_e.html#autotoc_md1',1,'']]],
  ['uma_20loja_20sendo_20usado_20o_20exemplo_20de_20uma_20loja_20de_20eletrônicos_23',['_Neste projeto temos o intuito de criar um programa capaz de realizar a administração da entrada e saída de produtos de uma loja, sendo usado o exemplo de uma loja de eletrônicos.',['../md__c_1_2_users_2fcgam_2_one_drive_2_documentos_2_t_f_2_controle-de-estoque-e-vendas-de-loja_2_r_e_a_d_m_e.html#autotoc_md1',1,'']]],
  ['unicode_24',['UNICODE',['../moc__predefs_8h.html#a09ecca53f2cd1b8d1c566bedb245e141',1,'moc_predefs.h']]],
  ['usado_20o_20exemplo_20de_20uma_20loja_20de_20eletrônicos_25',['_Neste projeto temos o intuito de criar um programa capaz de realizar a administração da entrada e saída de produtos de uma loja, sendo usado o exemplo de uma loja de eletrônicos.',['../md__c_1_2_users_2fcgam_2_one_drive_2_documentos_2_t_f_2_controle-de-estoque-e-vendas-de-loja_2_r_e_a_d_m_e.html#autotoc_md1',1,'']]]
];
