var searchData=
[
  ['da_20costa_20jardim_0',['_ Filipe da Costa Jardim',['../md__c_1_2_users_2fcgam_2_one_drive_2_documentos_2_t_f_2_controle-de-estoque-e-vendas-de-loja_2_r_e_a_d_m_e.html#autotoc_md9',1,'']]],
  ['da_20entrada_20e_20saída_20de_20produtos_20de_20uma_20loja_20sendo_20usado_20o_20exemplo_20de_20uma_20loja_20de_20eletrônicos_1',['_Neste projeto temos o intuito de criar um programa capaz de realizar a administração da entrada e saída de produtos de uma loja, sendo usado o exemplo de uma loja de eletrônicos.',['../md__c_1_2_users_2fcgam_2_one_drive_2_documentos_2_t_f_2_controle-de-estoque-e-vendas-de-loja_2_r_e_a_d_m_e.html#autotoc_md1',1,'']]],
  ['dadosdevenda_2',['dadosdevenda',['../class_dados_de_venda.html',1,'DadosDeVenda'],['../class_ui_1_1_dados_de_venda.html',1,'Ui::DadosDeVenda'],['../class_dados_de_venda.html#a8b78f83e8dbd8dd62601936aeb67a433',1,'DadosDeVenda::DadosDeVenda(QWidget *parent=nullptr)'],['../class_dados_de_venda.html#a8b78f83e8dbd8dd62601936aeb67a433',1,'DadosDeVenda::DadosDeVenda(QWidget *parent=nullptr)']]],
  ['dadosdevenda_2ecpp_3',['dadosdevenda.cpp',['../interface_2dadosdevenda_8cpp.html',1,'(Global Namespace)'],['../_projeto_final_2interface_2dadosdevenda_8cpp.html',1,'(Global Namespace)']]],
  ['dadosdevenda_2eh_4',['dadosdevenda.h',['../interface_2dadosdevenda_8h.html',1,'(Global Namespace)'],['../_projeto_final_2interface_2dadosdevenda_8h.html',1,'(Global Namespace)']]],
  ['das_20vendas_20de_20acordo_20com_20a_20quantidade_5',['_O programa apresentará ao final de um número específico de vendas, o produto mais vendido, o produto menos vendido e os demais com um cálculo em porcentagem das vendas de acordo com a quantidade.',['../md__c_1_2_users_2fcgam_2_one_drive_2_documentos_2_t_f_2_controle-de-estoque-e-vendas-de-loja_2_r_e_a_d_m_e.html#autotoc_md4',1,'']]],
  ['data_5ftxt_6',['Data_txt',['../class_ui___vender_produtos.html#a036d9d146abd9f050a20f275fc5c712f',1,'Ui_VenderProdutos']]],
  ['de_20criar_20um_20programa_20capaz_20de_20realizar_20a_20administração_20da_20entrada_20e_20saída_20de_20produtos_20de_20uma_20loja_20sendo_20usado_20o_20exemplo_20de_20uma_20loja_20de_20eletrônicos_7',['_Neste projeto temos o intuito de criar um programa capaz de realizar a administração da entrada e saída de produtos de uma loja, sendo usado o exemplo de uma loja de eletrônicos.',['../md__c_1_2_users_2fcgam_2_one_drive_2_documentos_2_t_f_2_controle-de-estoque-e-vendas-de-loja_2_r_e_a_d_m_e.html#autotoc_md1',1,'']]],
  ['de_20estoque_20e_20vendas_20de_20loja_8',['Controle de Estoque e Vendas de Loja.',['../md__c_1_2_users_2fcgam_2_one_drive_2_documentos_2_t_f_2_controle-de-estoque-e-vendas-de-loja_2_r_e_a_d_m_e.html',1,'']]],
  ['de_20produtos_20organizar_20por_20preço_20e_20ordem_20alfabética_9',['_Arquivar o tipo e quantidade de produtos,organizar por preço e ordem alfabética.',['../md__c_1_2_users_2fcgam_2_one_drive_2_documentos_2_t_f_2_controle-de-estoque-e-vendas-de-loja_2_r_e_a_d_m_e.html#autotoc_md3',1,'']]],
  ['de_20um_20número_20específico_20de_20vendas_20o_20produto_20mais_20vendido_20o_20produto_20menos_20vendido_20e_20os_20demais_20com_20um_20cálculo_20em_20porcentagem_20das_20vendas_20de_20acordo_20com_20a_20quantidade_10',['_O programa apresentará ao final de um número específico de vendas, o produto mais vendido, o produto menos vendido e os demais com um cálculo em porcentagem das vendas de acordo com a quantidade.',['../md__c_1_2_users_2fcgam_2_one_drive_2_documentos_2_t_f_2_controle-de-estoque-e-vendas-de-loja_2_r_e_a_d_m_e.html#autotoc_md4',1,'']]],
  ['debitando_20automaticamente_20do_20estoque_11',['_Nosso programa deve emitir a nota fiscal do produto vendido, debitando automaticamente do estoque.',['../md__c_1_2_users_2fcgam_2_one_drive_2_documentos_2_t_f_2_controle-de-estoque-e-vendas-de-loja_2_r_e_a_d_m_e.html#autotoc_md5',1,'']]],
  ['dec_12',['DEC',['../_c_make_c_x_x_compiler_id_8cpp.html#ad1280362da42492bbc11aa78cbf776ad',1,'CMakeCXXCompilerId.cpp']]],
  ['deletarpedido_13',['deletarpedido',['../class_funcionario.html#a0dc502b657989feb409f920b028496a2',1,'Funcionario::deletarPedido(Estoque *e)'],['../class_funcionario.html#a0dc502b657989feb409f920b028496a2',1,'Funcionario::deletarPedido(Estoque *e)']]],
  ['demais_20com_20um_20cálculo_20em_20porcentagem_20das_20vendas_20de_20acordo_20com_20a_20quantidade_14',['_O programa apresentará ao final de um número específico de vendas, o produto mais vendido, o produto menos vendido e os demais com um cálculo em porcentagem das vendas de acordo com a quantidade.',['../md__c_1_2_users_2fcgam_2_one_drive_2_documentos_2_t_f_2_controle-de-estoque-e-vendas-de-loja_2_r_e_a_d_m_e.html#autotoc_md4',1,'']]],
  ['deve_20emitir_20a_20nota_20fiscal_20do_20produto_20vendido_20debitando_20automaticamente_20do_20estoque_15',['_Nosso programa deve emitir a nota fiscal do produto vendido, debitando automaticamente do estoque.',['../md__c_1_2_users_2fcgam_2_one_drive_2_documentos_2_t_f_2_controle-de-estoque-e-vendas-de-loja_2_r_e_a_d_m_e.html#autotoc_md5',1,'']]],
  ['dia_5ftxt_16',['Dia_txt',['../class_ui___dados_de_venda.html#a7899d8f92dc675011a2b3bafe3b2b648',1,'Ui_DadosDeVenda']]],
  ['dinheiro_17',['_Gravar como o produto foi pago( cartão, pix e dinheiro).',['../md__c_1_2_users_2fcgam_2_one_drive_2_documentos_2_t_f_2_controle-de-estoque-e-vendas-de-loja_2_r_e_a_d_m_e.html#autotoc_md7',1,'']]],
  ['do_20produto_20vendido_20debitando_20automaticamente_20do_20estoque_18',['_Nosso programa deve emitir a nota fiscal do produto vendido, debitando automaticamente do estoque.',['../md__c_1_2_users_2fcgam_2_one_drive_2_documentos_2_t_f_2_controle-de-estoque-e-vendas-de-loja_2_r_e_a_d_m_e.html#autotoc_md5',1,'']]],
  ['do_20programa_19',['Funcionalidades do Programa',['../md__c_1_2_users_2fcgam_2_one_drive_2_documentos_2_t_f_2_controle-de-estoque-e-vendas-de-loja_2_r_e_a_d_m_e.html#autotoc_md2',1,'']]],
  ['do_20projeto_20',['Autores do Projeto',['../md__c_1_2_users_2fcgam_2_one_drive_2_documentos_2_t_f_2_controle-de-estoque-e-vendas-de-loja_2_r_e_a_d_m_e.html#autotoc_md8',1,'']]]
];
