var searchData=
[
  ['main_0',['main',['../_projeto_final_2interface_2main_8cpp.html#a0ddf1224851353fc92bfbff6f499fa97',1,'main(int argc, char *argv[]):&#160;main.cpp'],['../interface_2main_8cpp.html#a0ddf1224851353fc92bfbff6f499fa97',1,'main(int argc, char *argv[]):&#160;main.cpp'],['../_c_make_c_x_x_compiler_id_8cpp.html#a0ddf1224851353fc92bfbff6f499fa97',1,'main(int argc, char *argv[]):&#160;CMakeCXXCompilerId.cpp'],['../main_8cpp.html#a0ddf1224851353fc92bfbff6f499fa97',1,'main(int argc, char *argv[]):&#160;main.cpp']]],
  ['main_2ecpp_1',['main.cpp',['../_projeto_final_2interface_2main_8cpp.html',1,'(Global Namespace)'],['../main_8cpp.html',1,'(Global Namespace)'],['../interface_2main_8cpp.html',1,'(Global Namespace)']]],
  ['mainwindow_2',['mainwindow',['../class_main_window.html',1,'MainWindow'],['../class_ui_1_1_main_window.html',1,'Ui::MainWindow'],['../class_main_window.html#a996c5a2b6f77944776856f08ec30858d',1,'MainWindow::MainWindow(QWidget *parent=nullptr)'],['../class_main_window.html#a996c5a2b6f77944776856f08ec30858d',1,'MainWindow::MainWindow(QWidget *parent=nullptr)'],['../class_main_window.html#a996c5a2b6f77944776856f08ec30858d',1,'MainWindow::MainWindow(QWidget *parent=nullptr)']]],
  ['mainwindow_2ecpp_3',['mainwindow.cpp',['../_projeto_final_2interface_2mainwindow_8cpp.html',1,'(Global Namespace)'],['../mainwindow_8cpp.html',1,'(Global Namespace)'],['../interface_2mainwindow_8cpp.html',1,'(Global Namespace)']]],
  ['mainwindow_2eh_4',['mainwindow.h',['../_projeto_final_2interface_2mainwindow_8h.html',1,'(Global Namespace)'],['../mainwindow_8h.html',1,'(Global Namespace)'],['../interface_2mainwindow_8h.html',1,'(Global Namespace)']]],
  ['mais_20vendido_20o_20produto_20menos_20vendido_20e_20os_20demais_20com_20um_20cálculo_20em_20porcentagem_20das_20vendas_20de_20acordo_20com_20a_20quantidade_5',['_O programa apresentará ao final de um número específico de vendas, o produto mais vendido, o produto menos vendido e os demais com um cálculo em porcentagem das vendas de acordo com a quantidade.',['../md__c_1_2_users_2fcgam_2_one_drive_2_documentos_2_t_f_2_controle-de-estoque-e-vendas-de-loja_2_r_e_a_d_m_e.html#autotoc_md4',1,'']]],
  ['menos_20vendido_20e_20os_20demais_20com_20um_20cálculo_20em_20porcentagem_20das_20vendas_20de_20acordo_20com_20a_20quantidade_6',['_O programa apresentará ao final de um número específico de vendas, o produto mais vendido, o produto menos vendido e os demais com um cálculo em porcentagem das vendas de acordo com a quantidade.',['../md__c_1_2_users_2fcgam_2_one_drive_2_documentos_2_t_f_2_controle-de-estoque-e-vendas-de-loja_2_r_e_a_d_m_e.html#autotoc_md4',1,'']]],
  ['menubar_7',['menubar',['../class_ui___main_window.html#adf43d9a67adaec750aaa956b5e082f09',1,'Ui_MainWindow']]],
  ['menupagina_5finicial_8',['menuPagina_Inicial',['../class_ui___main_window.html#a15dc928830688dcfd57b668e595cb77a',1,'Ui_MainWindow']]],
  ['mingw_5fhas_5fsecure_5fapi_9',['MINGW_HAS_SECURE_API',['../moc__predefs_8h.html#a7652218632d79c675cce0c49732ee345',1,'moc_predefs.h']]],
  ['moc_5fadcionarfuncionarios_2ecpp_10',['moc_adcionarfuncionarios.cpp',['../moc__adcionarfuncionarios_8cpp.html',1,'']]],
  ['moc_5fadcionarfuncionarios_2ecpp_2ed_11',['moc_adcionarfuncionarios.cpp.d',['../moc__adcionarfuncionarios_8cpp_8d.html',1,'']]],
  ['moc_5fadproduto_2ecpp_12',['moc_adproduto.cpp',['../moc__adproduto_8cpp.html',1,'']]],
  ['moc_5fadproduto_2ecpp_2ed_13',['moc_adproduto.cpp.d',['../moc__adproduto_8cpp_8d.html',1,'']]],
  ['moc_5fdadosdevenda_2ecpp_14',['moc_dadosdevenda.cpp',['../moc__dadosdevenda_8cpp.html',1,'']]],
  ['moc_5fdadosdevenda_2ecpp_2ed_15',['moc_dadosdevenda.cpp.d',['../moc__dadosdevenda_8cpp_8d.html',1,'']]],
  ['moc_5fexibirdadosdevenda_2ecpp_16',['moc_exibirdadosdevenda.cpp',['../moc__exibirdadosdevenda_8cpp.html',1,'']]],
  ['moc_5fexibirdadosdevenda_2ecpp_2ed_17',['moc_exibirdadosdevenda.cpp.d',['../moc__exibirdadosdevenda_8cpp_8d.html',1,'']]],
  ['moc_5fexibirestoque_2ecpp_18',['moc_exibirestoque.cpp',['../moc__exibirestoque_8cpp.html',1,'']]],
  ['moc_5fexibirestoque_2ecpp_2ed_19',['moc_exibirestoque.cpp.d',['../moc__exibirestoque_8cpp_8d.html',1,'']]],
  ['moc_5fmainwindow_2ecpp_20',['moc_mainwindow.cpp',['../moc__mainwindow_8cpp.html',1,'']]],
  ['moc_5fmainwindow_2ecpp_2ed_21',['moc_mainwindow.cpp.d',['../moc__mainwindow_8cpp_8d.html',1,'']]],
  ['moc_5fpredefs_2eh_22',['moc_predefs.h',['../moc__predefs_8h.html',1,'']]],
  ['moc_5fproduto_2ecpp_23',['moc_produto.cpp',['../moc__produto_8cpp.html',1,'']]],
  ['moc_5fproduto_2ecpp_2ed_24',['moc_produto.cpp.d',['../moc__produto_8cpp_8d.html',1,'']]],
  ['moc_5fremoveproduto_2ecpp_25',['moc_removeproduto.cpp',['../moc__removeproduto_8cpp.html',1,'']]],
  ['moc_5fremoveproduto_2ecpp_2ed_26',['moc_removeproduto.cpp.d',['../moc__removeproduto_8cpp_8d.html',1,'']]],
  ['moc_5fvenderproduto_2ecpp_27',['moc_venderproduto.cpp',['../moc__venderproduto_8cpp.html',1,'']]],
  ['moc_5fvenderproduto_2ecpp_2ed_28',['moc_venderproduto.cpp.d',['../moc__venderproduto_8cpp_8d.html',1,'']]],
  ['moc_5fvenderprodutos_2ecpp_29',['moc_venderprodutos.cpp',['../moc__venderprodutos_8cpp.html',1,'']]],
  ['moc_5fvenderprodutos_2ecpp_2ed_30',['moc_venderprodutos.cpp.d',['../moc__venderprodutos_8cpp_8d.html',1,'']]],
  ['mocs_5fcompilation_2ecpp_31',['mocs_compilation.cpp',['../mocs__compilation_8cpp.html',1,'']]],
  ['moreira_20prado_32',['_ Bruno Moreira Prado',['../md__c_1_2_users_2fcgam_2_one_drive_2_documentos_2_t_f_2_controle-de-estoque-e-vendas-de-loja_2_r_e_a_d_m_e.html#autotoc_md10',1,'']]]
];
