// This file is autogenerated. Changes will be overwritten.
#include "XBG7L5Z4V6/moc_adcionarfuncionarios.cpp"
#include "XBG7L5Z4V6/moc_adproduto.cpp"
#include "XBG7L5Z4V6/moc_dadosdevenda.cpp"
#include "XBG7L5Z4V6/moc_exibirestoque.cpp"
#include "XBG7L5Z4V6/moc_mainwindow.cpp"
#include "XBG7L5Z4V6/moc_removeproduto.cpp"
#include "XBG7L5Z4V6/moc_venderprodutos.cpp"
